[
  {
    "fishID": 1,
    "region": "",
    "type": "Fish",
    "name": "Skyfish",
    "rarity": "Exotic",
    "set": "from the `Skyblyss` Set!",
    "MIN_WEIGHT": 350,
    "MAX_WEIGHT": 2500,
    "MIN_LENGTH": 21.7,
    "MAX_LENGTH": 79.7,
    "MIN_WIDTH": 0.6,
    "MAX_WIDTH": 2.9,
  },
  {
    "fishID": 2,
    "region": "",
    "type": "Developer",
    "name": "Hyperfish",
    "rarity": "Exotic",
    "set": "from the `Developer` set!",
    "MIN_WEIGHT": 375,
    "MAX_WEIGHT": 1337,
    "MIN_LENGTH": 1.2,
    "MAX_LENGTH": 7,
    "MIN_WIDTH": 0.2,
    "MAX_WIDTH": 0.9,
  },
  {
    "fishID": 3,
    "region": "",
    "type": "Frog",
    "name": "PogFrog",
    "rarity": "Exotic",
    "set": "from the `Twitch` set!",
    "MIN_WEIGHT": 325,
    "MAX_WEIGHT": 1337,
    "MIN_LENGTH": 2.7,
    "MAX_LENGTH": 8.6,
    "MIN_WIDTH": 0.2,
    "MAX_WIDTH": 0.8,
  },
  {
    "fishID": 4,
    "region": "1",
    "type": "Frog",
    "name": "Pepe",
    "rarity": "Exotic",
    "set": "from the `Memes` set!",
    "MIN_WEIGHT": 350,
    "MAX_WEIGHT": 1337,
    "MIN_LENGTH": 2.1,
    "MAX_LENGTH": 13.14,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.9,
  },
  {
    "fishID": 5,
    "region": "6",
    "type": "Fish",
    "name": "Sqid",
    "rarity": "Exotic",
    "set": "from the `Anmal` set!",
    "MIN_WEIGHT": 350,
    "MAX_WEIGHT": 1337,
    "MIN_LENGTH": 13.5,
    "MAX_LENGTH": 20.37,
    "MIN_WIDTH": 0.3,
    "MAX_WIDTH": 0.6,
  },
  {
    "fishID": 6,
    "region": "6",
    "type": "Fish",
    "name": "Chunkiest Kong",
    "rarity": "Exotic",
    "set": " from the `Alpha Testers` set!",
    "MIN_WEIGHT": 450,
    "MAX_WEIGHT": 1337,
    "MIN_LENGTH": 5.4,
    "MAX_LENGTH": 8.8,
    "MIN_WIDTH": 0.2,
    "MAX_WIDTH": 1,
  },
  {
    "fishID": 7,
    "region": "6",
    "type": "Fish",
    "name": "Slightly-Golden 18kt Goldfish",
    "rarity": "Legendary",
    "set": "from the `things that don\\`t belong here` set.",
    "MIN_WEIGHT": 12,
    "MAX_WEIGHT": 38,
    "MIN_LENGTH": 3,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 8,
    "region": "2",
    "type": "Fish",
    "name": "Bass",
    "rarity": "Legendary",
    "set": "",
    "MIN_WEIGHT": 10,
    "MAX_WEIGHT": 40,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 14,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.8,
  },
  {
    "fishID": 9,
    "region": "2",
    "type": "Fish",
    "name": "CHUNKIEST OF KONGS",
    "rarity": "Legendary",
    "set": "",
    "MIN_WEIGHT": 22,
    "MAX_WEIGHT": 300,
    "MIN_LENGTH": 5,
    "MAX_LENGTH": 30,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.6,
  },
  {
    "fishID": 10,
    "region": "6",
    "type": "Fish",
    "name": "Abyss Lurker",
    "rarity": "Legendary",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 45,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 12,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 11,
    "region": "1",
    "type": "Fish",
    "name": "BrickFish",
    "rarity": "Legendary",
    "set": "from the `things that don\\`t belong here` set.",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 12,
    "region": "2",
    "type": "Fish",
    "name": "Sturgeon",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 1,
    "MAX_WEIGHT": 153,
    "MIN_LENGTH": 1,
    "MAX_LENGTH": 20,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 13,
    "region": "2",
    "type": "Fish",
    "name": "Bass",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 1,
    "MAX_WEIGHT": 13,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 14,
    "region": "1",
    "type": "Fish",
    "name": "Guppy",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 0.07,
    "MAX_WEIGHT": 0.6,
    "MIN_LENGTH": 0.1,
    "MAX_LENGTH": 1,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 15,
    "region": "2",
    "type": "Fish",
    "name": "Salmon",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 1,
    "MAX_LENGTH": 6,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 16,
    "region": "2",
    "type": "Fish",
    "name": "Catfish",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 17,
    "region": "1",
    "type": "Fish",
    "name": "Goldfish",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 18,
    "region": "3",
    "type": "Fish",
    "name": "Betta-Fish",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 19,
    "region": "6",
    "type": "Fish",
    "name": "Cod",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 20,
    "region": "6",
    "type": "Fish",
    "name": "Anchovy",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 21,
    "region": "2",
    "type": "Fish",
    "name": "Asian Carp",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 22,
    "region": "6",
    "type": "Fish",
    "name": "Bream",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 23,
    "region": "3",
    "type": "Fish",
    "name": "Black Bream",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 24,
    "region": "6",
    "type": "Fish",
    "name": "Carp",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 25,
    "region": "2",
    "type": "Fish",
    "name": "Dace",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 26,
    "region": "1",
    "type": "Fish",
    "name": "Darter",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 27,
    "region": "3",
    "type": "Fish",
    "name": "Dory",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 28,
    "region": "3",
    "type": "Fish",
    "name": "Flounder",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 29,
    "region": "3",
    "type": "Fish",
    "name": "Grouper",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 30,
    "region": "3",
    "type": "Fish",
    "name": "Herring",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 31,
    "region": "3",
    "type": "Fish",
    "name": "Lampfish",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 32,
    "region": "3",
    "type": "Fish",
    "name": "Blue Bream",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 33,
    "region": "2",
    "type": "Fish",
    "name": "Minnow",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 34,
    "region": "2",
    "type": "Fish",
    "name": "Pacu",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 35,
    "region": "3",
    "type": "Fish",
    "name": "Piranha",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 36,
    "region": "3",
    "type": "Fish",
    "name": "Red Mullet",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 37,
    "region": "3",
    "type": "Fish",
    "name": "Red Seabream",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 38,
    "region": "6",
    "type": "Fish",
    "name": "Sea Bass",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 39,
    "region": "2",
    "type": "Fish",
    "name": "Snakefish",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 40,
    "region": "3",
    "type": "Fish",
    "name": "Tetra",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 41,
    "region": "3",
    "type": "Fish",
    "name": "Trout",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 42,
    "region": "",
    "type": "Fish",
    "name": "Larry The Blob Fish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 43,
    "region": "",
    "type": "Fish",
    "name": "Oranda Goldfish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 44,
    "region": "Mystical",
    "type": "Fish",
    "name": "Crystalish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 45,
    "region": "",
    "type": "Fish",
    "name": "Car Battery",
    "rarity": "Uncommon",
    "set": "from the `things that don\\`t belong here` set.\\n||Also charges the electrical eels.||",
    "MIN_WEIGHT": 1203,
    "MAX_WEIGHT": 2400,
    "MIN_LENGTH": 10,
    "MAX_LENGTH": 12,
    "MIN_WIDTH": 0.4,
    "MAX_WIDTH": 0.6,
  },
  {
    "fishID": 46,
    "region": "",
    "type": "Fish",
    "name": "Orc Fish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 5,
    "MAX_WEIGHT": 48,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 18,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 47,
    "region": "",
    "type": "Fish",
    "name": "Fried Fish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 48,
    "region": "",
    "type": "Fish",
    "name": "Scoob Fish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 6,
    "MAX_WEIGHT": 126,
    "MIN_LENGTH": 1.6,
    "MAX_LENGTH": 8,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 49,
    "region": "",
    "type": "Fish",
    "name": "Angelfish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 50,
    "region": "",
    "type": "Fish",
    "name": "Dolphin",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 51,
    "region": "Deep Ocean",
    "type": "Fish",
    "name": "Deep-Sea Wrangler",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 3750,
    "MAX_WEIGHT": 4830,
    "MIN_LENGTH": 8,
    "MAX_LENGTH": 14,
    "MIN_WIDTH": 0.4,
    "MAX_WIDTH": 0.65,
  },
  {
    "fishID": 52,
    "region": "",
    "type": "Fish",
    "name": "Golden Semilarvatus Butterflyfish",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 5,
    "MIN_LENGTH": 0.25,
    "MAX_LENGTH": 1,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 53,
    "region": "",
    "type": "Fish",
    "name": "Ghost Eel",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 0.7,
    "MAX_WEIGHT": 10,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 8,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.2,
  },
  {
    "fishID": 54,
    "region": "",
    "type": "Fish",
    "name": "Rainbow Trout",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 7,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 3,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 55,
    "region": "",
    "type": "Fish",
    "name": "Tuna",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 1508,
    "MIN_LENGTH": 0.2,
    "MAX_LENGTH": 12,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 56,
    "region": "",
    "type": "Fish",
    "name": "Murry the Moray Eel",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 17,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 13,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.25,
  },
  {
    "fishID": 57,
    "region": "",
    "type": "Fish",
    "name": "Squid",
    "rarity": "Rare",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 0.3,
    "MAX_LENGTH": 23,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 58,
    "region": "",
    "type": "Fish",
    "name": "Dolphin",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 59,
    "region": "",
    "type": "Fish",
    "name": "Gummy Hammerhead Shark",
    "rarity": "Epic",
    "set": "from the `Gummy Sharks` set.",
    "MIN_WEIGHT": 3750,
    "MAX_WEIGHT": 4830,
    "MIN_LENGTH": 8,
    "MAX_LENGTH": 14,
    "MIN_WIDTH": 0.4,
    "MAX_WIDTH": 0.65,
  },
  {
    "fishID": 60,
    "region": "",
    "type": "Fish",
    "name": "Golden Semilarvatus Butterflyfish",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 5,
    "MIN_LENGTH": 0.25,
    "MAX_LENGTH": 1,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 61,
    "region": "",
    "type": "Fish",
    "name": "Ghost Eel",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 0.7,
    "MAX_WEIGHT": 10,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 8,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.2,
  },
  {
    "fishID": 62,
    "region": "",
    "type": "Fish",
    "name": "Rainbow Trout",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 7,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 3,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 63,
    "region": "",
    "type": "Fish",
    "name": "Tuna",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 1508,
    "MIN_LENGTH": 0.2,
    "MAX_LENGTH": 12,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 64,
    "region": "",
    "type": "Fish",
    "name": "Murry the Moray Eel",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 0.5,
    "MAX_WEIGHT": 17,
    "MIN_LENGTH": 0.5,
    "MAX_LENGTH": 13,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.25,
  },
  {
    "fishID": 65,
    "region": "",
    "type": "Fish",
    "name": "Squid",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 0.3,
    "MAX_LENGTH": 23,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 66,
    "region": "",
    "type": "Fish",
    "name": "Kong Carp",
    "rarity": "Epic",
    "set": "",
    "MIN_WEIGHT": 24,
    "MAX_WEIGHT": 600,
    "MIN_LENGTH": 1.3,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 67,
    "region": "",
    "type": "Lobster",
    "name": "Shimp",
    "rarity": "Exotic",
    "set": "from the `Anmals` set.",
    "MIN_WEIGHT": 396,
    "MAX_WEIGHT": 1768,
    "MIN_LENGTH": 9.6,
    "MAX_LENGTH": 16.65,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 68,
    "region": "1",
    "type": "Fish",
    "name": "Breadfish",
    "rarity": "Uncommon",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 12,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 12,
    "MIN_WIDTH": 0.3,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 69,
    "region": "",
    "type": "Fish",
    "name": "Octpus",
    "rarity": "Exotic",
    "set": "from The `Anmals` Set!",
    "MIN_WEIGHT": 1250,
    "MAX_WEIGHT": 3001,
    "MIN_LENGTH": 12,
    "MAX_LENGTH": 20,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 3,
  },
  {
    "fishID": 70,
    "region": "5",
    "type": "Fish",
    "name": "Rainbow Boot",
    "rarity": "Daily",
    "set": "from the `Daily` Set!",
    "MIN_WEIGHT": 12345,
    "MAX_WEIGHT": 99999,
    "MIN_LENGTH": 0.6,
    "MAX_LENGTH": 1.6,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 71,
    "region": "4",
    "type": "Shark",
    "name": "Shark",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 72,
    "region": "4",
    "type": "Crocodile",
    "name": "Crocodile",
    "rarity": "Common",
    "set": "",
    "MIN_WEIGHT": 2,
    "MAX_WEIGHT": 30,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 73,
    "region": "",
    "type": "Fish",
    "name": "Stefph Bro",
    "rarity": "Exotic",
    "set": "from the `Skyblyss` Set!",
    "MIN_WEIGHT": 160,
    "MAX_WEIGHT": 440,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 60,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 2.7,
  },
  {
    "fishID": 74,
    "region": "",
    "type": "Fish",
    "name": "Lobter",
    "rarity": "Exotic",
    "set": "from the `VALORANT` set!",
    "MIN_WEIGHT": 200,
    "MAX_WEIGHT": 3000,
    "MIN_LENGTH": 6.18,
    "MAX_LENGTH": 17.6,
    "MIN_WIDTH": 1.25,
    "MAX_WIDTH": 2.4,
  },
  {
    "fishID": 75,
    "region": "",
    "type": "Fish",
    "name": "Skyblyss Fish",
    "rarity": "Exotic",
    "set": "from the `Twitch Streamers` set!",
    "MIN_WEIGHT": 424,
    "MAX_WEIGHT": 2245,
    "MIN_LENGTH": 4.5,
    "MAX_LENGTH": 16,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 0.7,
  },
  {
    "fishID": 76,
    "region": "",
    "type": "Fish",
    "name": "Bloodfish",
    "rarity": "Legendary",
    "set": "from the `Special` Series",
    "MIN_WEIGHT": 12,
    "MAX_WEIGHT": 20,
    "MIN_LENGTH": 2.5,
    "MAX_LENGTH": 10,
    "MIN_WIDTH": 0.1,
    "MAX_WIDTH": 4.7,
  }
 ]